org: manishhanmantraolokhande
app: general-services-app
service: general-services

provider:
 name: aws
 runtime: nodejs12.x
 apiGateway:
    binaryMediaTypes:
      - '*/*'
#  memorySize: 128
#  timeout: 10
#  stage: dev
 region: us-east-2
 credentials:
      accessKeyId: AKIAJZG6URPB6QEAUHNQ
      secretAccessKey: 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

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /